# Generated by Django 5.1.6 on 2026-06-14 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_likedmovie_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='_taste_vector',
            field=models.TextField(blank=True, db_column='taste_vector', null=True),
        ),
    ]
